---
variables:
  DOCKER_IMAGE: "CHANGE_ME"

stages:
  - lint
  - build

lint-dockerfile:
  stage: lint
  image: hadolint/hadolint:v1.17.1-3-g4017799-debian
  script:
    - hadolint --ignore DL3013 --ignore DL3018 --ignore DL3028 Dockerfile

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - \[ -z "$DOCKER_CONFIG" ] && export DOCKER_CONFIG=/kaniko/.docker
    - |
      cat > "${DOCKER_CONFIG}/config.json" <<EOF
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "username": "${DOCKERHUB_USER}",
            "password": "${DOCKERHUB_PASSWORD}"
          }
        }
      }
      EOF
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg=BUILD_DATE="$(date --utc +%Y-%m-%dT%H:%M:%SZ)"
      --build-arg=VCS_REF=${CI_COMMIT_SHA}
      --destination "${DOCKERHUB_USER}/${DOCKER_IMAGE}:${CI_COMMIT_REF_SLUG}"
      --destination "${DOCKERHUB_USER}/${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA}"
  except:
    - master
    - tags

build-master:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - \[ -z "$DOCKER_CONFIG" ] && export DOCKER_CONFIG=/kaniko/.docker
    - |
      cat > "${DOCKER_CONFIG}/config.json" <<EOF
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "username": "${DOCKERHUB_USER}",
            "password": "${DOCKERHUB_PASSWORD}"
          }
        }
      }
      EOF
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg=BUILD_DATE="$(date --utc +%Y-%m-%dT%H:%M:%SZ)"
      --build-arg=VCS_REF=${CI_COMMIT_SHA}
      --destination "${DOCKERHUB_USER}/${DOCKER_IMAGE}:${CI_COMMIT_REF_SLUG}"
      --destination "${DOCKERHUB_USER}/${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --destination "${DOCKERHUB_USER}/${DOCKER_IMAGE}:latest"
  only:
    - master

build-tag:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - \[ -z "$DOCKER_CONFIG" ] && export DOCKER_CONFIG=/kaniko/.docker
    - |
      cat > "${DOCKER_CONFIG}/config.json" <<EOF
      {
        "auths": {
          "https://index.docker.io/v1/": {
            "username": "${DOCKERHUB_USER}",
            "password": "${DOCKERHUB_PASSWORD}"
          }
        }
      }
      EOF
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --build-arg=BUILD_DATE="$(date --utc +%Y-%m-%dT%H:%M:%SZ)"
      --build-arg=VCS_REF=${CI_COMMIT_SHA}
      --destination "${DOCKERHUB_USER}/${DOCKER_IMAGE}:${CI_COMMIT_TAG}"
  only:
    - tags
